import { Product } from '../../types/product';

export const products: Product[] = [
  {
    id: '1',
    name: 'Burg Clássico',
    description: 'Um hambúrguer delicioso com carne de primeira.',
    price: 20.9,
    image: '/images/burg_classico.png',
    category: 'tradicional',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad29980d/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '2',
    name: 'Chicken cheese',
    description: 'Frango empanado com muito queijo e sabor.',
    price: 20.9,
    image: '/images/chicken_cheese.png',
    category: 'tradicional',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad29982b/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '3',
    name: 'Especial bacon',
    description: 'Hambúrguer com uma explosão de bacon.',
    price: 20.9,
    image: '/images/especial_bacon.png',
    category: 'tradicional',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad299849/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '4',
    name: 'Especial salada',
    description: 'Para os amantes de uma salada caprichada.',
    price: 20.9,
    image: '/images/especial_salada.png',
    category: 'tradicional',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad299867/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '5',
    name: 'TOURO ESTELAR',
    description: 'Um hambúrguer de outro mundo, literalmente.',
    price: 29.9,
    image: '/images/touro_estelar.png',
    category: 'especial',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad2998c1/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '6',
    name: 'COSMO BACON X2',
    description: 'Dobro de bacon, dobro de alegria.',
    price: 32.9,
    image: '/images/cosmo_baconx2.png',
    category: 'especial',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad2998df/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '7',
    name: 'ASTRO NEBULITOS',
    description: 'Textura, crocância e sabor em um só.',
    price: 31.9,
    image: '/images/astro_nebulitos.png',
    category: 'especial',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad2998a3/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '8',
    name: 'ORBITA VERDE',
    description: 'Sabor suave e leveza, direto do espaço.',
    price: 27.9,
    image: '/images/orbita_verde.png',
    category: 'especial',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad2998fd/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '11',
    name: 'GALACTUS',
    description: 'Um hambúrguer supremo e incomparável.',
    price: 49.9,
    image: '/images/galactus.png',
    category: 'supremos',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad29991b/0/nebs-burguer?categoryType=simple_item',
  },
  {
    id: '12',
    name: 'DORMAMMU',
    description: 'Poder, sabor e intensidade em cada mordida.',
    price: 49.9,
    image: '/images/dormammu.png',
    category: 'supremos',
    purchaseLink: 'https://pedido.anota.ai/product/67f7b5312eed62b4ad299975/0/nebs-burguer?categoryType=simple_item',
  },
];
